"""modelo_datos_completo_v2

Revision ID: a8b2d1f90d1d
Revises: 9c3f5d4c2a11
Create Date: 2026-04-17 16:08:14.935825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8b2d1f90d1d'
down_revision: Union[str, Sequence[str], None] = '9c3f5d4c2a11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
